spring.application.name=Transformers_Backend
spring.datasource.url=jdbc:mysql://localhost:3306/Transformers_DataBase
spring.datasource.username=root
spring.datasource.password=F1l@d3lf1@
spring.jpa.hibernate.ddl-auto=update